services:
  flask-app:
    build: .
    container_name: flask-app
    expose:
      - "5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app --timeout 0
    networks:
      - app-net

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - flask-app
    networks:
      - app-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --quiet --deploy-hook \"docker exec -it nginx-proxy nginx -s reload\"; sleep 12h & wait $${!}; done;'"

networks:
  app-net:
    external: true
